[state=h_background clavier]
= Asciidoc(tor)

[NOTE.speaker]
====
Gautier
Spec Asciidoc : Vient d'intégrer la fondation Eclipse (7 Janvier)
====

== Pourquoi cet outil ?

De nos constats...

[NOTE.speaker]
====
[N] Volonté d'aller vers la doc as code.
De rapprocher la doc du code (dans les dépots git)

Deux vrai possibilité : Markdown vs Asciidoctor
====

== Pourquoi cet outil ?

Une faiblesse qui peut être une force

Quelques simplicité syntaxiques

Gestion dans un Git

[NOTE.speaker]
====
Gautier ::
- Pas de problème de flavours (spec Asciidoc)
- Insertion de fragment de fichier
- Syntaxe plus cohérente
- Les devs ont les droits !
====

== Parce que la doc ce n'est pas toujours un long fleuve tranquille...

[NOTE.speaker]
====
Gautier

La doc as code, ca pose quand même des problèmes qu'on a pas autrement...
====

[state=v_background nappes]
==  Build & deploy

[NOTE.speaker]
====
[N] En Ruby, mais...

Accessible à tous, grace à Gradle ou JS
====

==  Build

```groovy
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'org.asciidoctor:asciidoctor-gradle-plugin:1.5.3'
        classpath 'org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.15'
    }
}
```

[NOTE.speaker]
====
Nicolas

Mise en place de build avec Graddle :::
- Syntaxe ulta simple
- Génération de PDF
====

==  Build

```groovy

asciidoctor {
    backends 'html5', 'pdf'
    dependsOn clean
    sourceDir = file('src/asciidoc')
    sources {
        include '**/*.adoc'
        exclude '**/content/**'
    }
    resources {
        from (sourceDir) {
            include '**/resources/**'
        }
    }
    outputDir = file('build/docs')
}
```

==  Deploy

Le Dockerfile le plus compliqué du monde

```
FROM nginx

COPY build/docs/html5 /usr/share/nginx/html
```

[NOTE.speaker]
====
Gautier

Déploiement Continue - Jenkins / Docker / NginX
====

==  Mais nos dépôts deviennent bordéliques

[state=v_background neurone]
==  Une structuration partagée

[NOTE.speaker]
====
Nicolas

- Plusieurs projets sur un plateau
- Pourquoi ne pas avoir une base commune ?
- Ce sont finalement les mêmes questqion qu'avec une doc traditionnelle
====

==  Une structuration partagée

* Démarrage - Quickstart
* Environnements - Environements
* Recommandation - Guidlines
* Manuels - How to

== Et si on avait plusieurs dépôts ?

TODO : Schéma (NGI)

[NOTE.speaker]
====
Nicolas

Comment la problématique d'agrégation a été prise en compte :::
- Dépot sous format zip des éléments générés
- Mise en place d'aggrégarteur via Dockerfile (schémas)
====