[state=h_background auto_stop]
= Points de départ

[NOTE.speaker]
====
Les contextes de nos aventuriers : mise en place du contexte initial avant le démarrage de notre migration

La documentation projet pour nous c'est : 

* Tout élément complémentaire au code qui permet de comprendre techniquement et / ou fonctionnellement un élément du produit. 
====

[state=v_background pepper]
== Qui sommes nous ?

Nicolas : 🐦 @nicgiro

[NOTE.speaker]
====
* Lead dev chez OnePoint
* Couteau suisse français de l'informatique
====

[state=v_background storm_papa]
== Qui sommes nous ?

Gautier : 🐦 @darkjabberwock

[NOTE.speaker]
====
* Freelance
* JUG Leader
* Contributeur opensource
====

== De l'utile...

Janvier 2017 : Début de projet "from scratch"

[NOTE.speaker]
====
[N]

Début d'un projet (01-17) from scratch en tant que lead dev en binome

 - Besoin de documenter ce qui est fait, mais peu de temps
 - Expérience passé en markdown, donc on fait quelques doc markdown, un peu de wiki
 - Doc contractuelle traditionnelle (suite bureautique)
 - Un binome contributeur Asciidoctor.js...
 - J'ai fuis au bout de 3 mois

====

[transition=zoom, %notitle]
== ...à l'indispensable

Janvier 2018 : Récupération d'un projet historique

[NOTE.speaker]
====
[N]

Nouveau projet (01-18) => mise en place de doc as code sans concessions
====

== Une nécessité...

Déjà sensibilisé à la Doc As Code

[NOTE.speaker]
====
[G]

Blog hubpress (asciidoctor sur github-pages) par un contributeur Asciidoctor.js....

Prise de note et slide deck (asciidoctor-revealjs) en adoc.
====

== ...devenue vitale

Septembre 2017 : Arrivé sur un projet de moins d'un an

[NOTE.speaker]
====
[G] Bien appuyer sur le fait que le projet c'est le même.

Arrivé en prestation sur un projet (09-17) (potentiellement le même !) dans le role de tech lead
Souhaite accéder à la documention :

 - Doc pas à jour
 - Absence de lead pendant un bon semestre
 - Doc dans des GED (format traditionnel)
 - Pas forcément tout les droits (presta)
====

[state=v_background pont]
== Le partage de connaissance


[NOTE.speaker]
====

Ce qui nous lie

Une sensibilité à la doc

Un seul but : Le partage de connaissance

====